title:              Shinimodori
email:              ShinimodoriTL@gmail.com
description:        He Challenges the Fight Fatefully.
author:             ｓｈｉｒｙｕ
baseurl:            ""
url:                "https://shinimodori.github.io"

# Social Profiles
twitter_username:   nissyhiro222
github_username:    
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-DWEZCBB47Z # UA-XXXXXXXXX-X # out your google-analytics code G-DWEZCBB47Z

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
permalink:          /:title/
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
